- [ ] Adjust speed, increase / decrease with controller triggers
- [ ] Do not lock screen
- [ ] Video Streaming to Android
- [ ] Tilt software / hardware
- [ ] UI, lots of UI
- [ ] Low battery checks (tablet, controller, drone)
- [ ] Estimated time of flight left
- [ ] Warning sounds
- [ ] Crash / signal lost control
- [ ] Record video on USB option
- [ ] Auto land system
- [ ] Remote actions (arm / disarm / shutdown / auto land? )
- [ ] On resume / on pause apk
- [ ] Data sent back to device, ALT, HEADING, ORIENTATION etc
- [ ] Password arm?
- [ ] On screen controls